{% set name = "pybytebuffer" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/PyByteBuffer-{{ version }}.tar.gz
  sha256: 5aa1e83c28bf5570d09bae0913937514325a7239e818220506baff8a8c0b51f9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - PyByteBuffer
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/iGio90/PyByteBuffer
  summary: A bytes manipulation library inspired by Java ByteBuffer
  license: GPL-3.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - nehaljwani
